### ISSUE TITLE
How to use the imageprocessing on Openwhisk?

### ISSUE THREAD

**Issue by liusy58** [ddps-lab/serverless-faas-workbench#13]
Hi, sir, I wonder how I can use the imageprocessing program on openwhisk.

Looking forward to your reply~

**Comment by kmu-leeky** [comment]
Hello.

Unfortunately, the current version does not support Openwhisk but support function run-times of public cloud vendors only. ?Modification considering openwhisk run-time seems necessary.

**Comment by liusy58** [comment]
What a pity! Okay, thx a lot~

**Comment by hyu-leeky** [comment]
It's been a while, but the porting to OpenWhisk was conducted in #37 .
