### ISSUE TITLE
Disk I/O intensive application

### ISSUE THREAD

**Issue by dgiantsidi** [ddps-lab/serverless-faas-workbench#24]
Hi there,

Could you please tell me an application that is disk-I/O intensive? I am aware of the microbenchmarks for the disk but I would like to also have a real-world application that stress-test the persistent storage.

I am running LogisticRegression() since the paper categorizes it as an application with medium I/O usage.
However the I/O looks like at most 5% of the execution time which seems that the app is CPU-bound (or memory-bound).

More info:

-  I am running the app locally (I mock the aws functions with local operations to the local fs). The function runs once.

-  The times I get for different input files are:

```
reviews10mb.csv
Fetching data from storage: 0.116973876953125
Preprocessing: 1.7436234951019287
Processing: 1.7523410320281982
```
```
reviews20mb.csv
Fetching data from storage: 0.21954607963562012
Preprocessing: 3.2018744945526123
Processing: 5.558855772018433
```
```
reviews50mb.csv
Fetching data from storage: 0.5435199737548828
Preprocessing: 8.798089027404785
Processing: 18.99028968811035
```
```
reviews100mb.csv
Fetching data from storage: 1.090895652770996
Preprocessing: 17.646488189697266
Processing: 44.82020878791809
```

Any guidance would be highly appreciated.

Thanks,
Dimitra

**Comment by kmu-leeky** [comment]
Hi Dimitra,

We had difficulties in finding practical I/O intensive applications initially when we first started to develop the benchmark suite. With recently introduced disk options to FaaS (NFS by using AWS EFS, supporting container image for a AWS Lambda runtime), we can imagine some practical I/O scenarios. 

One example that we heavily use is embedding DNN model packages (python, tensorflow, numpy, …) into a container image which requires quite heavy read overhead in case of cold-start. Another possible scenario might be model inferencing using an ensemble method which requires loading a large number of models for inference. Both cases are mostly read-intensive workloads, though.
