### ISSUE TITLE
google - gzip_compression

### ISSUE THREAD

**Issue by baddoghaus** [ddps-lab/serverless-faas-workbench#25]
Hello,

To the best of my knowledge when opening the file_write_path the second time the mode should be set to 'rb'. Very well could have been left off for a good reason, and I could be wrong. Thank you.

    with open(file_write_path, **'rb'**) as f:
        start = time()
        with gzip.open('/tmp/result.gz', 'wb') as gz:
            gz.writelines(f)
        compress_latency = time() - start

**Comment by kmu-leeky** [comment]
Thank you for the report @baddoghaus 

In Lambda, the local file path does not linger after the invoke, and we cannot make sure the /tmp/result.gz would exist in the same path. Thus, it should create a new file in the path whenever it runs.
