### ISSUE TITLE
google - ml_video_face_detection

### ISSUE THREAD

**Issue by baddoghaus** [ddps-lab/serverless-faas-workbench#36]
I believe line 12 of serverless-faas-workbench/google/cpu-memory/model_serving/ml_video_face_detection/main.py should be changed from **fourcc = cv2.VideoWriter_fourcc(*'XVID')** to **fourcc = cv2.VideoWriter.fourcc(*'XVID')**

That is change the **_** to a **.**

**Comment by kmu-leeky** [comment]
Hi @baddoghaus

Thank you for the report. In the code, we are referring to a case in the following page.

https://www.programcreek.com/python/example/89348/cv2.VideoWriter_fourcc

Do you see any issue that it should be changed to fourcc method?

**Comment by baddoghaus** [comment]
Hello @kmu-leeky and thanks for the response.

My apologies, I was just able to successfully run my function with the source code you've provided. My true error was a mismatch of video codec formats.

**Comment by kmu-leeky** [comment]
thank you for the update. good to hear that.
